Exception in thread "AWT-EventQueue-0"
java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at java.util.ArrayList.rangeCheck(ArrayList.java:653)
	at java.util.ArrayList.remove(ArrayList.java:492)
	at Player.getCard(Player.java:53)
	at WarGame.step(WarGame.java:51)
	
	Here is the issue and what needs to be fixed. Seems as if a card is
getting removed when there isnt anything to remove.